family_office_statistics/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import bad_request, permission_denied, page_not_found, server_error

from .views import HomepageView, PrivacyPolicyView, TermsOfUseView, RequestAnInviteView, ContactUsView

urlpatterns = [
    # Homepage
    url(
        r'^$',
        view=HomepageView.as_view(),
        name="home"
    ),
    url(r'^account/',
        include('account.urls')
    ),
    url(r'^portfolio/',
        include('portfolios.urls', namespace="portfolios")
    ),
    url(r'^privacy_policy$', PrivacyPolicyView.as_view(), name='privacy_policy'),
    url(r'^terms_of_use$', TermsOfUseView.as_view(), name='terms_of_use'),
    url(r'^contact_us$', ContactUsView.as_view(), name='contact_us'),

    url(r'^request_an_invite$', include('invitation.urls', namespace='invitation')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [

        url(r'^__debug__/$',
            include(debug_toolbar.urls)
        ),

        # This allows the error pages to be debugged during development, just visit
        # these URLs in browser to see how these error pages look.
        url(
            regex=r'^400/$',
            view=bad_request,
            name='400_demo'
        ),
        url(
            regex=r'^403/$',
            view=permission_denied,
            name='403_demo'
        ),
        url(
            regex=r'^404/$',
            view=page_not_found,
            name='404_demo'
        ),
        url(
            regex=r'^500/$',
            view=server_error,
            name='500_demo'
        ),

    ]


# URLs for non-local apps
urlpatterns += [
    
    # Django Admin Documentation
    url(r'^admin/doc/',
        include('django.contrib.admindocs.urls')
    ),

    # Django Admin
    url(r'^admin/',
        include(admin.site.urls)
    ),

    # Third-party app URLs
    url(r'^captcha/',
        include('captcha.urls')
    ),
    url(r'^markdown/',
        include('django_markdown.urls')
    ),

]

family_office_statistics/portfolios/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.PortfolioView.as_view(),
        name="detail"
    ),
    url(r'^update/',
        include([
            url(
                regex=r'^percentages/$',
                view=views.PortfolioPercentagesUpdateView.as_view(),
                name="update_percentages"
            ),
            url(
                regex=r'^amounts/$',
                view=views.PortfolioAmountsUpdateView.as_view(),
                name="update_amounts"
            )
        ])
    ),
    # url(
    #     r'^create/',
    #     include([
    #         url(
    #             regex=r'^$',
    #             view=views.portfolio_wizard,
    #             name='wizard'
    #         ),
    #         url(
    #             regex=r'^(?P<step>[-\w]+)/$',
    #             view=views.portfolio_wizard,
    #             name='wizard_step'
    #         ),
    #     ])
    # ),
    url(r'^create/',
        include([
            url(
                regex=r'^percentages/$',
                view=views.PortfolioPercentagesCreateView.as_view(),
                name='create_percentages'
            ),
            url(
                regex=r'^amounts/$',
                view=views.PortfolioAmountsCreateView.as_view(),
                name='create_amounts'
            ),
            url(
                regex=r'^$',
                view=views.PortfolioCreationMethodChoiceView.as_view(),
                name='create'
            ),
        ])
    ),
    url(
        regex=r'^delete/$',
        view=views.PortfolioDeleteView.as_view(),
        name="delete"
    ),
]

family_office_statistics/portfolios/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals, division
from math import floor, fsum
from decimal import Decimal

from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.forms.models import model_to_dict
from django.shortcuts import redirect, get_object_or_404
from django.utils.translation import ugettext as _
from django.views.generic import (TemplateView, DetailView, FormView,
    CreateView, UpdateView, DeleteView)

from braces.views import LoginRequiredMixin, UserPassesTestMixin
from formtools.wizard.views import NamedUrlSessionWizardView

from . import forms
from .models import Portfolio, AmountsPortfolio
from .utils import get_all_averages, get_category_average


class PortfolioView(LoginRequiredMixin, DetailView):
    """
    Display an individual user's :model:`portfolios.Portfolio`.

    **Context**

    ``user_portfolio``
        An instance of :model:`portfolios.Portfolio` belonging to the
        current authenticated user.
    ``tabular_data``
        A list of three-item lists. In order, the three items are:
            - Label for asset class type
            - Value for the user portfolio's asset class type
            - Average value for that asset class type across all
              :model:`portfolios.Portfolio` instances in the database.
    
    """
    context_object_name = "portfolio"
    template_name = 'portfolios/portfolio_detail.html'

    def get_object(self):
        queryset = Portfolio.objects.all()
        if queryset.filter(user=self.request.user).exists():
            obj = queryset.get(user=self.request.user)
        else:
            obj = None
        return obj

    def get_context_data(self, **kwargs):
        context = super(PortfolioView, self).get_context_data(**kwargs)

        amounts_queryset = AmountsPortfolio.objects.filter(user=self.request.user)
        context['dollar_amounts_used'] = amounts_queryset.exists()

        portfolio = self.get_object()
        if portfolio is not None:
            data = [[field['label'], float(field['value'])] for field in portfolio.get_all_fields()]
            averages = get_all_averages()
            for i in range(len(data)):
                data[i].append(float(averages[i]))

            context['tabular_data'] = data
            
            for choice in Portfolio.CATEGORY_CHOICES:
                context['your_{}_total'.format(choice)] = portfolio.get_category_total(choice)
                context['{}_average'.format(choice)] = float(get_category_average(choice))

        return context


class PortfolioCreationMethodChoiceView(LoginRequiredMixin, TemplateView):
    template_name = "portfolios/creation_method_choice.html"

    def dispatch(self, request, *args, **kwargs):
        user_amounts_portfolio = AmountsPortfolio.objects.filter(user=request.user)
        user_portfolio = Portfolio.objects.filter(user=request.user)
        if user_amounts_portfolio.exists() or user_portfolio.exists():
            raise PermissionDenied()
        return super(PortfolioCreationMethodChoiceView, self).dispatch(request, *args, **kwargs)


class PortfolioPercentagesCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Simple view for creating an individual user's
    :model:`portfolios.Portfolio`, with all form fields on one page.

    """
    form_class = forms.PortfolioPercentagesForm
    template_name = 'portfolios/portfolio_percentages_create_form.html'
    success_url = reverse_lazy('portfolios:detail')
    success_message = "Your portfolio was successfully created."

    def dispatch(self, request, *args, **kwargs):
        user_amounts_portfolio = AmountsPortfolio.objects.filter(user=request.user)
        user_portfolio = Portfolio.objects.filter(user=request.user)
        if user_amounts_portfolio.exists() or user_portfolio.exists():
            raise PermissionDenied()
        return super(PortfolioPercentagesCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PortfolioPercentagesCreateView, self).form_valid(form)


class PortfolioAmountsCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create an individual user's :model:`portfolios.portfolio`.

    """
    model = AmountsPortfolio
    form_class = forms.PortfolioAmountsForm
    template_name = 'portfolios/portfolio_amounts_form.html'
    success_url = reverse_lazy('portfolios:detail')
    success_message = "Your portfolio was successfully created."

    def dispatch(self, request, *args, **kwargs):
        user_amounts_portfolio = AmountsPortfolio.objects.filter(user=request.user)
        user_portfolio = Portfolio.objects.filter(user=request.user)
        if user_amounts_portfolio.exists() or user_portfolio.exists():
            raise PermissionDenied()
        return super(PortfolioAmountsCreateView, self).dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        data = form.cleaned_data
        total = Decimal(fsum(data.values()))
        percentages = dict()

        for label, val in data.items():
            percentages[label] = val/total * 100

        new_portfolio = Portfolio.objects.create(user=self.request.user, **percentages)

        form.instance.user = self.request.user

        return super(PortfolioAmountsCreateView, self).form_valid(form)


class PortfolioPercentagesUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update an individual user's existing :model:`portfolios.Portfolio`.

    """
    form_class = forms.PortfolioPercentagesForm
    template_name = 'portfolios/portfolio_percentages_update_form.html'
    success_url = reverse_lazy('portfolios:detail')
    success_message = "Your portfolio was successfully updated."

    def dispatch(self, request, *args, **kwargs):
        if AmountsPortfolio.objects.filter(user=request.user).exists():
            raise PermissionDenied()
        return super(PortfolioPercentagesUpdateView, self).dispatch(request, *args, **kwargs)

    def get_object(self):
        user_portfolio = get_object_or_404(Portfolio, user=self.request.user)
        return user_portfolio


class PortfolioAmountsUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update an individual user's existing :model:`portfolios.Portfolio`.

    """
    form_class = forms.PortfolioAmountsForm
    template_name = 'portfolios/portfolio_amounts_form.html'
    success_url = reverse_lazy('portfolios:detail')
    success_message = "Your portfolio was successfully updated."

    def get_object(self):
        user_portfolio = get_object_or_404(AmountsPortfolio, user=self.request.user)
        return user_portfolio

    def form_valid(self, form):
        data = form.cleaned_data
        total = Decimal(fsum(data.values()))
        percentages = dict()

        for label, val in data.items():
            percentages[label] = val/total * 100

        Portfolio.objects.filter(user=self.request.user).update(**percentages)

        return super(PortfolioAmountsUpdateView, self).form_valid(form)


class PortfolioDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """
    Delete an individual user's existing :model:`portfolio.Portfolio`.

    """
    template_name = "portfolios/portfolio_confirm_delete.html"
    success_url = reverse_lazy('home')
    success_message = "Your portfolio was successfully deleted."

    def get_object(self):
        user_portfolio = get_object_or_404(Portfolio, user=self.request.user)
        return user_portfolio

    def delete(self, request, *args, **kwargs):
        AmountsPortfolio.objects.filter(user=request.user).delete()
        return super(PortfolioDeleteView, self).delete(request, *args, **kwargs)


class PortfolioWizardView(LoginRequiredMixin, NamedUrlSessionWizardView):
    """
    Step-by-step view for creating an individual user's
    :model:`portfolios.Portfolio`.

    Unlike :view:`portfolios.PortfolioPercentagesCreateView`, the form is broken
    up across multiple pages.

    """
    template_name = "portfolios/portfolio_wizard_form.html"
    form_list = (
        ("equities", forms.PortfolioEquitiesForm),
        ("real_estate", forms.PortfolioRealEstateForm),
        ("bonds", forms.PortfolioBondsForm),
        ("commodities", forms.PortfolioCommoditiesForm),
        ("venture", forms.PortfolioVentureForm),
        ("other", forms.PortfolioOtherForm),
        ("review", forms.PortfolioEmptyConfirmationForm)
    )
    instance = None

    def dispatch(self, request, *args, **kwargs):
        user_portfolio = Portfolio.objects.filter(user=request.user)
        if user_portfolio.exists():
            raise PermissionDenied("You already have a portfolio.")

        if 'wizard_portfolio_wizard_view' not in request.session:
            request.session['has_data'] = False
        else:
            request.session['has_data'] = True

        if request.session['has_data']:
            if 'all_steps_visited' not in request.session['wizard_portfolio_wizard_view']:
                request.session['wizard_portfolio_wizard_view']['all_steps_visited'] = False

        return super(PortfolioWizardView, self).dispatch(request, *args, **kwargs)

    def get_form_instance(self, step):
        if self.instance is None:
            self.instance = Portfolio(user=self.request.user)
        return self.instance

    def get_form_initial(self, step):
        return self.initial_dict.get(step, {'user': self.request.user})

    def get_form_kwargs(self, step):
        if step == 'review':
            return {'request': self.request}
        else:
            return {}

    def get_context_data(self, form, **kwargs):

family_office_statistics/portfolios/templates/portfolios/_field_bootstrap_with_addon.html
<div id="wrapper-{{ field.auto_id }}" class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="col-sm-5 col-md-4 col-lg-3 control-label {{ classes.label }}{% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
    <div class="col-sm-7 col-md-8 col-lg-9">
      <div class="input-group">
        <span class="input-group-addon">$</span>
        {{ field }}
      </div>
    </div>
    {% for error in field.errors %}
      <div class="col-sm-7 col-sm-offset-5 col-md-8 col-md-offset-4 col-lg-9 col-lg-offset-3">
        <span class="help-block">{{ error }}</span>
      </div>
    {% endfor %}
    
    {% if field.help_text %}
    <div class="col-sm-7 col-sm-offset-5 col-md-8 col-md-offset-4 col-lg-9 col-lg-offset-3">
      <p class="help-block">
        {{ field.help_text|safe }}
      </p>
    </div>
    {% endif %}
</div>

family_office_statistics/portfolios/templates/portfolios/creation_method_choice.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block head_title %}
  FOA | Create Portfolio
{% endblock head_title %}

{% block body_base %}
  <section id="content_body">
    <div class="container">
      <h1>Create a new Portfolio</h1>
      <p class="lead">How would you like to create your portfolio?</p>
        <div class="row">
          <div class="col-sm-6">

            <div class="well">
              <p class="h5 text-center text-semibold">Option 1</p>
              <h2 class="h5 text-center text-normal">Enter dollar amounts<br><i class="small text-semibold">(easier, but less private)</i></h2>
              <p>Percentage allocations will be caluclated from the dollar amounts you enter; however, these amounts will be stored. If you are okay with us storing this information, this choice might be for you.</p>
              <p class="text-center"><br>
                <a href="{% url 'portfolios:create_amounts' %}" class="btn btn-lg btn-primary">Choose dollar amounts</a>
              </p>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="well">
              <p class="h5 text-center text-semibold">Option 2</p>
              <h2 class="h5 text-center text-normal">Enter percentages directly<br><i class="small text-semibold">(more private, but more work)</i></h2>
              <p>You can enter percentages directly. This will keep information about your portfolio size private, but the process takes longer and is generally more work.</p>
              <p class="text-center"><br><br class="visible-sm visible-md">
                <a href="{% url 'portfolios:create_percentages' %}" class="btn btn-lg btn-default">Choose percentages</a>
              </p>
            </div>
          </div>
        </div>
        
    </div>
  </section>
{% endblock body_base %}

family_office_statistics/portfolios/templates/portfolios/portfolio_confirm_delete.html
{% extends "site_base.html" %}
{% load i18n staticfiles bootstrap %}


{% block body_base %}
<section id="content_body">
  <div class="container">
    <h1 class="hidden">Delete Your Portfolio</h1>
    <form action="{% url 'portfolios:delete' %}" method="post">{% csrf_token %}
      <div class="alert alert-danger">
        <p class="h2"><strong>Are you sure you want to delete your portfolio?</strong></p>
        <hr>
        <button type="submit" class="btn btn-lg btn-danger">Yes, delete my portfolio</button>
      </div>
    </form>
  </div>
</section>
{% endblock body_base %}

family_office_statistics/portfolios/templates/portfolios/portfolio_detail.html
{% extends "site_base.html" %}
{% load i18n staticfiles bootstrap %}

{% block head_title %}FOA | {% trans "Portfolio" %}{% endblock %}

{% block body_class %}default{% endblock %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'portfolios/css/portfolio_detail.css' %}">
{% endblock styles %}

{% block extra_head %}

    <script src="{% static 'js/smartresize.js' %}"></script>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1.1", {packages:["bar"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Asset Class Category', 'Your Portfolio', 'Index/Baseline'],
          ['Equities', {{ your_equities_total }}, {{ equities_average }}],
          ['Real Estate', {{ your_real_estate_total }}, {{ real_estate_average }}],
          ['Bonds', {{ your_bonds_total }}, {{ bonds_average }}],
          ['Commodities', {{ your_commodities_total }}, {{ commodities_average }}],
          ['Venture Investments', {{ your_venture_total }}, {{ venture_average }}],
          ['Other', {{ your_other_total }}, {{ other_average }}]
        ]);

        var options = {
          chart: {
            title: 'Portfolio Allocations',
            subtitle: 'Asset classes as percentage of portfolio',
          }
        };

        var chart = new google.charts.Bar(document.getElementById('chart'));

        chart.draw(data, options);

        $(window).smartresize(function(){
          drawChart();
        });


      }
    </script>

{% endblock extra_head %}

{% block scripts %}
  {{ block.super }}
  <script>
    $(document).ready(function() {
      
      $('tr[data-toggle="collapse"]').click(function() {
        $(this).toggleClass("collapsed")
      }) 

      $('[rel="tooltip"]').tooltip()

    });
  </script>
{% endblock scripts %}

{% block body %}

  <div class="page-header no-top-margin">
    {% if portfolio %}
      <div class="btn-toolbar pull-right">
        <div class="btn-group">
          <a href="{% if dollar_amounts_used %}{% url 'portfolios:update_amounts' %}{% else %}{% url 'portfolios:update_percentages' %}{% endif %}" class="btn btn-primary"><i class="fa fa-edit"></i>&ensp;{% trans "Edit portfolio" %}</a>
        </div>
        <div class="btn-group">
          <a href="{% url 'portfolios:delete' %}" class="btn btn-danger"><i class="fa fa-trash"></i>&ensp;{% trans "Delete portfolio" %}</a>
        </div>
      </div>
    {% endif %}
    <h1 class="no-top-margin">
      {% if portfolio %}

        <small>{% trans "Portfolio" %}:</small> {{ portfolio.user.get_username }}
      {% else %}
        {% trans "Your Portfolio" %}
      {% endif %}
    </h1>

  </div>

  {% if not portfolio %}
    <div class="alert alert-warning" role="alert">
      <p class="lead">{% trans "You have not yet created a portfolio." %}</p>
      <hr>
      <p><a href="{% url 'portfolios:create' %}" class="btn btn-lg btn-warning">{% trans "Create one now" %}</a></p>
    </div>
  {% else %}
    <div class="row">
      <div class="col-md-8">
        <div class="table-responsive">
          <table class="table table-hover">
            <caption>{% blocktrans %}Your Portfolio <strong>(click a row to show/hide details)</strong>{% endblocktrans %}</caption>

            <thead>
              <tr>
                <th rowspan="2">{% trans "Asset Class" %}</th>
                <th colspan="2" class="text-center">{% trans "% of Portfolio" %}</th>
              </tr>

              <tr>
                <th>{% trans "Your Portfolio" %}</th>
                <th>{% trans "Index/Baseline" %}</th>
              </tr>

            </thead>

            <tbody>
              {% for category_label, value, average in tabular_data %}
                {% if forloop.counter == 1 %}
                  <tr class="active collapsed" data-toggle="collapse" data-target=".equities" title="click to expand/collapse" rel="tooltip" data-placement="right" aria-expanded="false">
                    <th>{% trans "Equities" %}</th>
                    <td>{{ your_equities_total|floatformat:"-2" }}</td>
                    <td>{{ equities_average|floatformat:"-2" }}</td>
                  </tr>
                {% elif forloop.counter == 11 %}
                  <tr class="active collapsed" data-toggle="collapse" data-target=".real-estate" title="click to expand/collapse" rel="tooltip" data-placement="right" aria-expanded="false">
                    <th>{% trans "Real Estate" %}</th>
                    <td>{{ your_real_estate_total|floatformat:"-2" }}</td>
                    <td>{{ real_estate_average|floatformat:"-2" }}</td>
                  </tr>
                {% elif forloop.counter == 15 %}
                  <tr class="active collapsed" data-toggle="collapse" data-target=".bonds" title="click to expand/collapse" rel="tooltip" data-placement="right" aria-expanded="false">
                    <th>{% trans "Bonds" %}</th>
                    <td>{{ your_bonds_total|floatformat:"-2" }}</td>
                    <td>{{ bonds_average|floatformat:"-2" }}</td>
                  </tr>
                {% elif forloop.counter == 22 %}
                  <tr class="active collapsed" data-toggle="collapse" data-target=".commodities" title="click to expand/collapse" rel="tooltip" data-placement="right" aria-expanded="false">
                    <th>{% trans "Commodities" %}</th>
                    <td>{{ your_commodities_total|floatformat:"-2" }}</td>
                    <td>{{ commodities_average|floatformat:"-2" }}</td>
                  </tr>
                {% elif forloop.counter == 24 %}
                  <tr class="active collapsed" data-toggle="collapse" data-target=".venture" title="click to expand/collapse" rel="tooltip" data-placement="right" aria-expanded="false">
                    <th>{% trans "Venture Investments" %}</th>
                    <td>{{ your_venture_total|floatformat:"-2" }}</td>
                    <td>{{ venture_average|floatformat:"-2" }}</td>
                  </tr>
                {% elif forloop.counter == 26 %}
                  <tr class="active collapsed" data-toggle="collapse" data-target=".other" title="click to expand/collapse" rel="tooltip" data-placement="right" aria-expanded="false">
                    <th>{% trans "Other" %}</th>
                    <td>{{ your_other_total|floatformat:"-2" }}</td>
                    <td>{{ other_average|floatformat:"-2" }}</td>
                  </tr>
                {% endif %}

                {% cycle 'equities' 'equities' 'equities' 'equities' 'equities' 'equities' 'equities' 'equities' 'equities' 'equities' 'real-estate' 'real-estate' 'real-estate' 'real-estate' 'bonds' 'bonds' 'bonds' 'bonds' 'bonds' 'bonds' 'bonds' 'commodities' 'commodities' 'venture' 'venture' 'other' 'other' 'other' 'other' 'other' 'other' as data_target silent %}

                <tr class="collapse {{ data_target }}">
                  <th>{{ category_label|capfirst }}</th>
                  <td>{{ value|floatformat:"-2" }}</td>
                  <td>{{ average|floatformat:"-2" }}</td>
                </tr>

              {% empty %}
              {% endfor %}

            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12 col-md-12">
        <figure id="chart" class="chart"></figure><br>
      </div>
    </div>
    

  {% endif %}

{% endblock body %}

family_office_statistics/portfolios/templates/portfolios/portfolio_form_base.html
{% extends "site_base.html" %}

{% load i18n staticfiles bootstrap %}

{% block head_title %}FOA | {% block form_head_title %}{% endblock %} Portfolio{% endblock head_title %}

{% block body_class %}default{% endblock %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'portfolios/css/portfolio_form.css' %}">
{% endblock styles %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'portfolios/js/portfolio-form.js' %}"></script>
  <script src="{% static 'portfolios/js/bottom-bar.js' %}"></script>
{% endblock scripts %}

{% block body_base %}
<section id="content_body">
  <div class="container">
    <div id="bottom-bar" class="navbar navbar-fixed-bottom navbar-default">
      <div class="container">
        <p class="navbar-text"><span class="wrapper">{% trans "Running Total" %}: <span id="running-total"></span></span></p>
      </div>
    </div>
    
    <form action="{% block form_action %}{% endblock %}" method="post" class="form-horizontal">{% csrf_token %}

      <div class="page-header no-top-margin">
        <a href="{% url 'portfolios:delete' %}" class="btn btn-danger pull-right"><i class="fa fa-trash-o"></i>&ensp;Delete Portfolio</a>
        <h1 class="no-top-margin">{% block form_title %}{% endblock %} {% trans "Portfolio" %}</h1>
      </div>
    

      <fieldset id="main-controls">
        <p>{% trans "What percentage of your portfolio is allocated toward the following asset classes?" %}</p>

        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
          </div>
        {% endif %}

          <fieldset>
            <legend>{% trans "Equities" %}</legend>
            {% for field in form  %}
              {% if forloop.counter >= 1 and forloop.counter <= 10 %}
                {{ field|bootstrap_horizontal }}
              {% endif %}
            {% endfor %}
          </fieldset>

          <fieldset>
            <legend>{% trans "Real Estate" %}</legend>
            {% for field in form %}
              {% if forloop.counter >= 11 and forloop.counter <= 14 %}
                {{ field|bootstrap_horizontal }}
              {% endif %}
            {% endfor %}
          </fieldset>

          <fieldset>
            <legend>{% trans "Bonds" %}</legend>
            {% for field in form  %}
              {% if forloop.counter >= 15 and forloop.counter <= 21 %}
                {{ field|bootstrap_horizontal }}
              {% endif %}
            {% endfor %}
          </fieldset>

          <fieldset>
            <legend>{% trans "Commodities" %}</legend>
            {% for field in form  %}
              {% if forloop.counter >= 22 and forloop.counter <= 23 %}
                {{ field|bootstrap_horizontal }}
              {% endif %}
            {% endfor %}
          </fieldset>

          <fieldset>
            <legend>{% trans "Venture" %}</legend>
            {% for field in form  %}
              {% if forloop.counter >= 24 and forloop.counter <= 25 %}
                {{ field|bootstrap_horizontal }}
              {% endif %}
            {% endfor %}
          </fieldset>

          <fieldset>
            <legend>{% trans "Other" %}</legend>
            {% for field in form  %}
              {% if forloop.counter >= 26 %}
                {{ field|bootstrap_horizontal }}
              {% endif %}
            {% endfor %}
          </fieldset>

      </fieldset>

      <fieldset id="buttons">
        <div class="form-group">
          <div class="col-sm-offset-5 col-sm-7 col-md-offset-4 col-md-8">
            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> {% trans "Finish" %}</button>
            <button type="reset" class="btn btn-default"><i class="fa fa-eraser"></i> {% trans "Clear fields" %}</button>
          </div>
        </div>
      </fieldset>
    
    </form>
  </div>
</section>
{% endblock body_base %}

family_office_statistics/portfolios/templates/portfolios/portfolio_percentages_create_form.html
{% extends "portfolios/portfolio_form_base.html" %}
{% load staticfiles i18n bootstrap%}

{% block form_action %}{% url 'portfolios:create_percentages' %}{% endblock %}

{% block form_head_title %}Create{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'portfolios/js/pcf-autofocus.js' %}"></script>
{% endblock %}

{% block form_title %}Create{% endblock %}

family_office_statistics/portfolios/templates/portfolios/portfolio_percentages_update_form.html
{% extends "portfolios/portfolio_form_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load bootstrap %}

{% block form_action %}{% url 'portfolios:update_percentages' %}{% endblock %}

{% block form_head_title %}Edit{% endblock %}

{% block form_title %}Edit{% endblock %}