family_office_statistics/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import bad_request, permission_denied, page_not_found, server_error

from .views import HomepageView, PrivacyPolicyView, TermsOfUseView, RequestAnInviteView, ContactUsView

urlpatterns = [
    # Homepage
    url(
        r'^$',
        view=HomepageView.as_view(),
        name="home"
    ),
    url(r'^account/',
        include('account.urls')
    ),
    url(r'^portfolio/',
        include('portfolios.urls', namespace="portfolios")
    ),
    url(r'^privacy_policy$', PrivacyPolicyView.as_view(), name='privacy_policy'),
    url(r'^terms_of_use$', TermsOfUseView.as_view(), name='terms_of_use'),
    url(r'^contact_us$', ContactUsView.as_view(), name='contact_us'),

    url(r'^request_an_invite$', include('invitation.urls', namespace='invitation')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [

        url(r'^__debug__/$',
            include(debug_toolbar.urls)
        ),

        # This allows the error pages to be debugged during development, just visit
        # these URLs in browser to see how these error pages look.
        url(
            regex=r'^400/$',
            view=bad_request,
            name='400_demo'
        ),
        url(
            regex=r'^403/$',
            view=permission_denied,
            name='403_demo'
        ),
        url(
            regex=r'^404/$',
            view=page_not_found,
            name='404_demo'
        ),
        url(
            regex=r'^500/$',
            view=server_error,
            name='500_demo'
        ),

    ]


# URLs for non-local apps
urlpatterns += [
    
    # Django Admin Documentation
    url(r'^admin/doc/',
        include('django.contrib.admindocs.urls')
    ),

    # Django Admin
    url(r'^admin/',
        include(admin.site.urls)
    ),

    # Third-party app URLs
    url(r'^captcha/',
        include('captcha.urls')
    ),
    url(r'^markdown/',
        include('django_markdown.urls')
    ),

]

family_office_statistics/invitation/urls.py
from django.conf.urls import url, include
from .views import InvitationView

urlpatterns = [
    url(r'^$', InvitationView.as_view(), name='request_an_invite')
]

family_office_statistics/portfolios/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.PortfolioView.as_view(),
        name="detail"
    ),
    url(r'^update/',
        include([
            url(
                regex=r'^percentages/$',
                view=views.PortfolioPercentagesUpdateView.as_view(),
                name="update_percentages"
            ),
            url(
                regex=r'^amounts/$',
                view=views.PortfolioAmountsUpdateView.as_view(),
                name="update_amounts"
            )
        ])
    ),
    # url(
    #     r'^create/',
    #     include([
    #         url(
    #             regex=r'^$',
    #             view=views.portfolio_wizard,
    #             name='wizard'
    #         ),
    #         url(
    #             regex=r'^(?P<step>[-\w]+)/$',
    #             view=views.portfolio_wizard,
    #             name='wizard_step'
    #         ),
    #     ])
    # ),
    url(r'^create/',
        include([
            url(
                regex=r'^percentages/$',
                view=views.PortfolioPercentagesCreateView.as_view(),
                name='create_percentages'
            ),
            url(
                regex=r'^amounts/$',
                view=views.PortfolioAmountsCreateView.as_view(),
                name='create_amounts'
            ),
            url(
                regex=r'^$',
                view=views.PortfolioCreationMethodChoiceView.as_view(),
                name='create'
            ),
        ])
    ),
    url(
        regex=r'^delete/$',
        view=views.PortfolioDeleteView.as_view(),
        name="delete"
    ),
]

family_office_statistics/templates/_account_bar.html
{% load i18n account_tags %}


<ul class="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-fw fa-user"></i> <b>{% user_display request.user %}</b> <span class="caret"></span></a>
            <ul class="dropdown-menu bg-inverse">
                    <li>
                        <a href="{% url 'account_settings' %}"><i class="fa fa-fw fa-cog"></i> Account Settings</a>
                    </li>
                    <li>
                        <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-fw fa-sign-out"></i> {% trans "Sign out" %}</a>
                    </li>
                {% if request.user.is_staff %}
                    <li class="divider" role="separator"></li>
                    <li>
                        <a href="{% url 'admin:index' %}"><i class="fa fa-fw fa-wrench"></i> {% trans "Admin" %}</a>
                    </li>
                {% endif %}
            </ul>
        </li>

    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Sign in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Register" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

family_office_statistics/templates/_footer.html
<div class="row">
<div class="col-xs-4 col-xs-offset-4 text-center">

	<div class="text-center">
		<a class="privacy-policy-link" href="{% url 'contact_us' %}">Contact Us</a>
	</div>
	<div class="text-center">
		<a class="terms-of-use-link" href="{% url 'terms_of_use' %}">Terms of Use</a>
	</div>
	<div class="text-center">
		<a class="privacy-policy-link" href="{% url 'privacy_policy' %}">Privacy Policy</a>
	</div>
	
 </div>
 
 <div class="col-xs-4">
 <div class="text-right">

 	&copy; {% now "Y" %} Family Office Statistics LLC
 
  </div>
</div>
</div>

family_office_statistics/templates/_messages.html
{% load pinax_theme_bootstrap_tags %}
{% for message in messages %}
    <div class="alert fade in {% get_message_tags message %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}

family_office_statistics/templates/_scripts.html
{% load staticfiles %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

family_office_statistics/templates/_styles.html
{% load staticfiles %}
{# <link rel="stylesheet" href="{% static 'css/crimson-text.css' %}"> #}
<link rel="stylesheet" href="{% static 'css/source-serif-pro.css' %}">
<link rel="stylesheet" href="{% static 'css/source-sans-pro.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/site_base.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

family_office_statistics/templates/contact_us.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Not Found" %}{% endblock %}

{% block body %}
    <header class="jumbotron subhead" id="overview">
        <h1>{% trans "Get in contact with us" %}</h1>
        <h2>Please send all questions and comments to:</h2>
        <h3><strong>info@familyofficestatistics.com</strong></h3>
    </header>
{% endblock %}

family_office_statistics/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n staticfiles %}

{% block head_title %}Family Office Statistics{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
  <section id="intro-banner" class="jumbotron" style="background-image: url({% static 'images/homepage/bg_woman_yacht.jpg' %})">
    <div class="container">
      {% include "_messages.html" %}
      <div class="row">
        <div class="col-md-8 col-lg-9 mobile-centered">
          <h1 class="no-top-margin">{% trans "See How Your Portfolio Compares" %}</h1>
          <p>
            {% trans "Be confident in your financial decisions by comparing your portfolio allocations to those of other ultra high&ndash;net-worth families." %}
          </p>
          
        </div>
      </div>
      <div class="row">
        <div class="{% if user.is_authenticated %}col-sm-6 col-md-5 col-lg-4{% else %}col-sm-12{% endif %}">
          {% if user.is_authenticated %}

            {% if user_portfolio %}
              <a href="{% url 'portfolios:detail' %}" class="btn btn-lg btn-primary btn-block">
                {% trans "View your portfolio" %}
              </a>
            {% else %}
              <a href="{% url 'portfolios:create' %}" class="btn btn-lg btn-primary btn-block">
                {% trans "Create your portfolio now" %}
              </a>
            {% endif %}

          {% else %}
            <a href="{% url 'account_signup' %}" class="btn btn-lg btn-primary">
              {% trans "Register an account" %}
            </a>&emsp;or&emsp;
            <a href="{% url 'account_login' %}" class="btn btn-lg btn-default">
              {% trans "Sign in" %}
            </a>
          {% endif %}

        </div>{# /.col- #}
      </div>{# /.row #}
    </div>{# /.container #}
  </section>
  
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <h2 class="h1">An Invitation-Only Resource for Sophisticated Investors</h2>
          <p class="lead">
            {% trans "Our collaborative, yet fully-private online resource provides a qualitative and quantitative data solution for families with highly active single-family offices to compare their portfolio allocations to those of other private families." %}
          </p>
        </div>
      </div>
    </div>
  </section>
  <section class="bg-inverse">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <h3 class="text-center">{% trans "Investment Pattern Analysis" %}</h3>
          <img src="{% static 'images/homepage/icon_pattern.svg' %}" alt="Investment Pattern Analysis" class="feature-icon img-responsive center-block">
          <p>
            {% trans "With data from many families, we are able to detect lucrative patterns in investment choices and portfolio allocation, giving you insight into better diversification." %}
          </p>
        </div>
        <div class="col-sm-4">
          <h3 class="text-center">{% trans "Real-Time Visuals" %}</h3><br class="visible-sm">
          <img src="{% static 'images/homepage/icon_predictive.svg' %}" alt="Investment Pattern Analysis" class="feature-icon img-responsive center-block">
          <p>
             {% trans "We offer a rich, engaging visual experience that allows you to easily understand and compare your portfolio data in real time to different datasets from peer families." %}
          </p>
        </div>
        <div class="col-sm-4">
          <h3 class="text-center">{% trans "Predictive Technology" %}</h3>
          <img src="{% static 'images/homepage/icon_visuals.svg' %}" alt="Investment Pattern Analysis" class="feature-icon img-responsive center-block">
          <p>
            {% trans "By interpreting the answers to common investing questions, we are able to provide predictive technology that will allow your family to make better informed decisions." %}
          </p>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="h1 text-center">How Does it Work?</h2>
          <p class="lead">
            {% trans "Once you have accepted an exclusive invitation to the FOS network, you will be asked a series of questions about the current allocation of your portfolio investments. Your data will be fully anonymized to protect your family's identity. This member-provided data will be combined with propritary and publicly-available market data to provide you real-time feedback on how your portfolio compares to those of your peers." %}
          </p>
        </div>
      </div>
    </div>
  </section>

  {% if not user.is_authenticated %}
  <section class="bg-gray-lighter">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="h1 text-center">{% trans "Learn More about the FOS Network" %}</h2>
          <p class="lead">{% trans "We are highly selective in our membership. Members must meet certain criteria before an invitation is extended. If you are interested in inquiring about membership, please contact us below." %}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 col-md-offset-4 col-md-4 col-lg-4">
          <a href="{% url 'invitation:request_an_invite' %}" class="btn btn-lg btn-primary btn-block" >
            {% trans "Request an Invitation" %}
          </a>
        </div>
      </div>
    </div>
  </section>
  {% endif %}
{% endblock %}

family_office_statistics/templates/privacy_policy.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Not Found" %}{% endblock %}

{% block body %}
    <header class="jumbotron subhead" id="overview">
        <h1>{% trans "Privacy Policy" %}</h1>
    </header>

<h1>Family Office Statistics Website Privacy Policy</h1>
<h2>Introduction</h2>
<p>Family Office Statistics LLC (“FOS”) respects your privacy and is committed to protecting it through our compliance with this Website Privacy Policy (“Policy”).  This Policy describes the types of information we may collect from you or that you may provide when you visit the Family Office Statistics Website, available at http://www.familyofficestatistics.com/ (the “FOS Website” or “Website”) and our practices for collecting, using, maintaining, protecting and disclosing that information.
<p></p>This Policy applies to information we collect on or through the Website.  It does not apply to information collected by us offline or through any other means.  
</p>
<p>Please read this Policy carefully to understand our policies and practices regarding your information and how we will treat it.  If you do not agree with our policies and practices, you may choose not to use the FOS Website. By accessing or using the FOS Website, you agree to this Policy, which is incorporated into and forms a part of the Visitor Agreement governing your use of the Website. This Policy may change from time to time. Your continued use of the FOS Website after we make changes is deemed to be acceptance of those changes, so please check this Policy periodically for updates. 
<p></p>The FOS Website may contains link to other websites. FOS is not responsible for the privacy practices of such linked websites; you should review the privacy policies of any linked website that you may visit.</p>

<h2>Information We Collect About You and How We Collect It</h2>
<p>We may collect several types of information from and about users of the FOS Website, including:
</p>

<p>1.	Information That You Provide to Us.  This includes information that you provide you when complete forms on the FOS Website or when you register or login to use the FOS Website, which may include your email address  or Login Credentials.  It also includes information that you provide when you engage in actions or use services offered on the FOS Website, such as your answers to investment questionnaires. We limit the personally-identifiable information collected from you on the FOS Website to that information necessary for us to verify your Login Credentials and grant access to the FOS Website to authorized users. 
</p>
<p>2.	Information About Your Use of the Website That We Collect Through Automated Data Collection Technologies. As you navigate through and interact with the FOS Website, we may use automated data collection technologies to collect certain information about your equipment, browsing actions and patterns, including:
<br>&#149;		Details of your visits to our Website, such as pages viewed and the resources that you access and use on the Website and
</p>

<p>&#149;		Information about your Internet connection, the equipment you use to access our Website and usage details, including your IP address, computer operating system and browser type.
</p>
<p>The information we may collect automatically is statistical data and does not include personally identifiable information, but we may maintain it or associate it with personally identifiable information that you may provide to us.  Such information helps us to improve our Website and to deliver a better and more personalized service to you, including by enabling us to store information about your preferences and recognize you when you return to the Website.  
</p>
<p>The technologies we use for this automatic data collection may include cookies, which are small files placed on the hard drive of your computer. You may refuse to accept cookies, but in that case you may be unable to access certain parts of our Website. 
</p>
<h2>How We Use Your Information</h2>
<p>We may use information that we collect about you or that you provide to us via the FOS Website for any lawful purpose.  Generally, we use such information for purposes of presenting the FOS Website and its features and contents to you, improving the FOS Website, communicating with you, and responding to your inquiries and requests.  We may also use such information for other purposes, including but not limited to investigating violation of our Visitor Agreement. 
</p>
<p>FOS may use information provided in response to investment questionnaires in anonymized form (“Anonymized Investment Information”) to analyze investment patterns and provide comparative data to our users.  Anonymized Investment Information may be used alone, or in combination with Anonymized Investment Information from other users, other proprietary data, or publicly-available market data for statistical analysis and reporting to users.  In addition, FOS reserves the right to use, publish, license, distribute or sell Anonymized Investment Information, and information derived therefrom, in aggregate form, for any purpose, including business development or investment purposes. 
</p>
<p>FOS strives to maintain the highest level of confidentiality with respect to its members’ personally identifiable information. FOS does not sell or rent its members’ personally identifiable information.  
</p>
<h2>Disclosure of Your Information</h2>
<p>We may disclose aggregated information about our users, and information that does not identify any particular user, without restriction. 
</p>
<p>We may disclose personally identifiable information that we collect or you provide as described in this Policy:
</p>
<p>&#149;		To our parent companies, subsidiaries and affiliates, if any;</p>
<p>&#149;		To contractors, service providers and other third parties we use to support our business provided they have agreed to maintain such information in confidence.</p>
<p>&#149;		To a buyer or other successor in the event of a corporate transaction, dissolution or other sale or transfer of some or all of FOS’s assets, in which personally identifiable information held by FOS about our Website users or members is among the assets transferred;</p>
<p>&#149;		To fulfill the purpose for which you provide it, including, but not limited to, to verify qualifications for membership, to communicate with you, and to respond to your requests;</p>
<p>&#149;		For any other purpose disclosed by us when you provide the information;</p>
<p>&#149;		With your consent.</p>
<h3>We may also disclose your personally identifiable information:</h3>
<p>&#149;		To comply with any court order, law or legal process, including to respond to any government or regulatory request;
</p>
<p>&#149;		To enforce our Visitor Agreement;</p>
<p>&#149;		If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of FOS, our members or others.</p> 
<p>FOS will not intentionally disclose in any public manner the personally identifiable information or identities of its users or members, or disclose investment questionnaire responses in such a way that they are or can be associated with the user or member who provided those responses. 
</p>
<h2>Choices About How We Use and Disclose Your Information</h2>
<p>We strive to provide you with choices regarding the personally identifiable information you provide to us. Following are ways that you can control your information: 
</p>
<p>&#149;		Adjusting your browser settings or </p>
<p>&#149;		Opting out of receiving news and offerings from FOS by sending an opt-out request to FOS or following the instructions in our communications to Unsubscribe or Opt-out.</p>
<h2>Data Security</h2>
<p>The security of your information is important to us.  We have implemented measures designed to secure your personally identifiable information and other data from accidental loss and from unauthorized access, use or disclosure.  The safety and security of your information also depends on you. Where we have given you (or where you have chosen) a password for access to certain portions of the FOS Website, you are responsible for keeping this password confidential. We ask you not to share your password with anyone, and be sure to close out of browser sessions in which you have accessed password-protected portions of the FOS Website. 
<p></p>Unfortunately, however, no technological protections are perfect, and the transmission of information via the Internet is not completely secure. Although we do our best to protect your personally identifiable and other information, we cannot guarantee the security of information that you may provide on our Website. Any transmission of personally identifiable information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website.
</p>
<h2>Changes to Our Privacy Policy</h2>
<p>It is our practice to post any changes we make to our Policy on this page.  The date the Policy was last revised is identified at the bottom of this page. You are responsible for ensuring we have an up-to-date, active and deliverable e-mail address for you, and for periodically visiting this page to check for any changes.
</p>
<h2>Contact Information</h2>
<p>If you have questions about this Policy, or wish to review or change any personally identifiable information that you may have provided to us, please contact us at: 
</p>
<p>Family Office Statistics LLC
500 West Putnam Avenue, Suite 400
Greenwich, Connecticut 06830 / Ph: 203-570-2898</p> 

<p> Please note that we cannot delete your personally identifiable information from our records except by also deleting your user account (if applicable). Nor can we accommodate a request to change information if we believe the change would violate any legal requirement or cause the information to be incorrect.
</p>
<h4 style="padding-bottom:2rem;">Last Updated:  January 1, 2015
</h4>

{% endblock %}

family_office_statistics/templates/request_an_invite.html
{% extends "site_base.html" %}

{% load account_tags %}
{% load i18n %}

{% load bootstrap %}

{% block head_title %}{% trans "Not Found" %}{% endblock %}

{% block body %}
<div class="col-sm-4 col-sm-offset-4">
    <h2>Get an invite code</h2>
    <p>We will reach out to you soon!</p>
<form method="post" action="{{ request.path }}">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
    </table>
        
    

<button type="submit" class="btn btn-success btn-block">Request a code</button>
</form>
</div>
{% endblock %}

family_office_statistics/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}
{% load staticfiles i18n metron_tags %}



{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block nav %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}">Home</a></li>
        {% if request.user.is_authenticated %}
            {% if user_portfolio %}
                <li><a href="{% url 'portfolios:detail' %}">Your Portfolio</a></li>
            {% endif %}
        {% endif %}
    </ul>
{% endblock nav %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}